// Will remove this after auth implementation

export const encodedToken =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiJhNGFmNzg0My04ZGUwLTRhYjUtOGRlMy1mNzlkMTYyZmQ5ZGIiLCJlbWFpbCI6ImFkYXJzaGJhbGlrYUBnbWFpbC5jb20ifQ.7lDIPNlh8da2ECODaDJXiorm17YFSLGnroDD9ZZDiUY";
